### ISSUE TITLE
detection in gazebo

### ISSUE THREAD

**Issue by ican9595** [introlab/find-object#114]
Hi @matlabbe,

I am trying to detect objects in gazebo but I have some issues.
When I add the objects from the scene I am able to detect them and get the right Pose as seen in the pictures below.
Simulation Environment:
![gazebo](https://user-images.githubusercontent.com/78037107/120318601-546fad80-c2e0-11eb-9ad1-799ff663692a.png)

Detection:
![fast_brisk_teach](https://user-images.githubusercontent.com/78037107/120319101-eb3c6a00-c2e0-11eb-968a-4de4183be76a.png)

I have added each object from every possible angle and saved it in a folder (in total 73 png files). When I launch it with the objects_path set the objects show up as expected.

But once I am navigating with the robot through the rows with the objects randomly spawned within the rows I have trouble detecting them.
![fast_brisk_run](https://user-images.githubusercontent.com/78037107/120319651-89303480-c2e1-11eb-9d9d-9a871bb08cc0.png)

I have tried different variations of the Parameters, Detectors/Descriptors etc. but couldn't get the wished results.

Do you have any suggestions how I can solve this? Maybe you can tell me which Detector/Descriptor and Parameters I should change?

Thank you in advance.

best regards 

Ibrahim

**Comment by matlabbe** [comment]
Hi,

For small objects like that and not too much texture on them, I think you would get better results with machine learning approaches, like [YOLO](https://pjreddie.com/darknet/yolo/) (maybe in combination with TLD "Tracking–learning–detection" [tracker](https://learnopencv.com/object-tracking-using-opencv-cpp-python/)). If you are planning to do this outside in real environment, because of the lighting is varying a lot, a machine learning approach may be better to detect those objects and to distinguish between plants vs ground vs objects.

For feature-based object detection like find-object, you would need higher resolution images, or detecting them closer to be able to extract more visual features on them.

cheers,
Mathieu

**Comment by ican9595** [comment]
Okay thank you very much. I am going to try YOLO. I could get better results with your package when I snipped the objects from a closer distance and set the camera closer to the ground so it could extraxt more features.
