### ISSUE TITLE
Question: What happens when multiple objects of the same type are found?

### ISSUE THREAD

**Issue by mincrmatt12** [introlab/find-object#30]
I'm planning to use this for a ROS project soon, and it has to find two tennis balls. Will it publish two different TF frames for the separate tennis balls?

**Comment by matlabbe** [comment]
Hi,

Yes it will, see the [find_object_2d](http://wiki.ros.org/find_object_2d#A3D_position_of_the_objects) page. To detect multiple occurrences of the same object, parameter \"General/multiDetection\" should be [checked](https://github.com/introlab/find-object/wiki/MultiDetection).  **However**, find-object won't work with tennis balls, because the object detection approach is based on local visual feature correspondences.

cheers,
Mathieu

**Comment by matlabbe** [comment]
see https://github.com/introlab/find-object/issues/54
