### ISSUE TITLE
Question: I'm detecting the same Object four times using Multidetection but only get one set of coordinates.

### ISSUE THREAD

**Issue by PKran** [introlab/find-object#54]
Hello,
I'm using find object to detect multiple Objects of the same kind. in order to pick one up I need to have its coordinates, but the multidetection only publishes one set of coordinates. Is there a way to fix that? All the objects get detected using the same ID.
Thank you,
Phil

**Comment by matlabbe** [comment]
Hi Phil,

The 3D example didn't work with multiDetection enabled. I updated the code so that it can work. See referred commit above. Some results:
![screenshot_2018-05-29_14-49-54](https://user-images.githubusercontent.com/2319645/40679049-21eef7be-6350-11e8-830e-23559bfaebef.png)

Note however there are no guarantees that "object_1" and "object_1_b" will refer to always to same object (e.g., TF may swap between both between detections).

cheers,
Mathieu

**Comment by PKran** [comment]
Hi Mathieu,

The code you provided does exactly what I was trying do to.
Tank you very much.
