### ISSUE TITLE
wow.I have Some minor details problem

### ISSUE THREAD

**Issue by zhangstar3** [introlab/find-object#90]
hi.I'm very sorry, but I want to ask you a few questions.
i have test the demo,When two objects are matched, a rectangle is drawn in the main window.
But i have look through the findobject.cpp and rectItem.cpp,
i have maybe a little confused,i could not find which line you are draw a rectangle.
if hope you can help me which file doing this work ,thanks!!
because i want to put some text in the object by myself work.

**Comment by matlabbe** [comment]
The RectItem is added to main ObjWidget scene here:
https://github.com/introlab/find-object/blob/5047163c09df5515bc505341c279045c8d9c503c/src/MainWindow.cpp#L1433-L1437

The actual draw function is done by the GraphicsView by simply adding the RectItem to it [here](https://github.com/introlab/find-object/blob/5047163c09df5515bc505341c279045c8d9c503c/src/ObjWidget.cpp#L381), if ObjWidget is in GraphicsView mode. Otherwise, in not GraphicsView mode, the rectangle is drawn manually [here](https://github.com/introlab/find-object/blob/5047163c09df5515bc505341c279045c8d9c503c/src/ObjWidget.cpp#L524-L531) on the widget.

cheers,
Mathieu

**Comment by zhangstar3** [comment]
hello,very thanks,I started off in the wrong direction.
then,i will try to make some changes.
